### ISSUE TITLE
Script stops with a 404 dropbox rest error on some files

### ISSUE THREAD

**Issue by 1000mb** [clark800/dropbox-restore#16]
dropbox.rest.ErrorResponse: [404] u"Path XXXXXX not found

I worked round this by wrapping:
            if item.get('is_dir', False):
                restore_folder(client, item['path'], cutoff_datetime, verbose)
            else:
                restore_file(client, item['path'], cutoff_datetime,
                    item.get('is_deleted', False), verbose)
(lines 81 to 85)
in a try, catch block so that these files would be skipped and the restore continue.

**Comment by YBthebest** [comment]
I am getting the same error. No solution?

**Comment by clark800** [comment]
I can't reproduce this, so there's no way to debug it. Please provide as much information as you can so that someone can figure it out at some point.

**Comment by dtb** [comment]
I ran into this with a shared folder, idk if that helps. 

Here was the stack

~~~~
Traceback (most recent call last):
  File "restore.py", line 103, in <module>
    main()
  File "restore.py", line 99, in main
    restore_folder(client, root_path, cutoff_datetime, verbose=True)
  File "restore.py", line 84, in restore_folder
    restore_folder(client, item['path'], cutoff_datetime, verbose)
  File "restore.py", line 84, in restore_folder
    restore_folder(client, item['path'], cutoff_datetime, verbose)
  File "restore.py", line 87, in restore_folder
    item.get('is_deleted', False), verbose)
  File "restore.py", line 47, in restore_file
    revisions = client.revisions(path.encode('utf8'))
  File "/Library/Python/2.7/site-packages/dropbox/client.py", line 1041, in revisions
    return self.rest_client.GET(url, headers)
  File "/Library/Python/2.7/site-packages/dropbox/rest.py", line 311, in GET
    return cls.IMPL.GET(*n, **kw)
  File "/Library/Python/2.7/site-packages/dropbox/rest.py", line 246, in GET
    return self.request("GET", url, headers=headers, raw_response=raw_response)
  File "/Library/Python/2.7/site-packages/dropbox/rest.py", line 227, in request
    raise ErrorResponse(r, r.read())
dropbox.rest.ErrorResponse: [404] u"Path '/some/shared/folder/file.jpg' not found"
~~~~

Also the file was super old, but it had just barely been added to my dropbox today. Maybe revision history works different for shared folders or something?

Thanks so much for this script!

**Comment by jcvikl** [comment]
this is my experience:
-- if you have free dropbox account insert into restore.py line 104 "cutoff_datetime).days >= 30", if you have pro dropbox account insert   "cutoff_datetime).days >= 365"
-- if you get error - script stops with a 404 dropbox rest error on some files like dropbox.rest.ErrorResponse: [404] u"Path '/some/shared/folder/file.jpg' not found" repeat command on same directory python2.7 restore.py /robert/../  2016-06-25
Many times script goes through, seems Dropbox or our server has capacity problems.
- I got error many times as: ..."Path '/hi 2' not found" Note: You must specify the path starting with "/", where "/" is the root of your dropbox folder. So if your dropbox directory is at "/home/user/dropbox" and you want to restore "/home/user/dropbox/folder", the ROOTPATH is "/folder".
I help myself to define names as they have blank space so I insert into command 
python2.7 restore.py /robert/My Documents/  2016-06-25 
blank space linux command: 
python2.7 restore.py /robert/"My Documents"/  2016-06-25
so you can solve blank spaces with "Folder name"
--  i run restore 2 times by folder for sure.


APPENDIX: If you need help contact me over http://marcelino.si because many newcomer havent root server access.

Have a nice day, bye
