### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by Cookie12** [clark800/dropbox-restore#28]
After a bunch of files...
Traceback (most recent call last):
  File "restore.py", line 103, in <module>
    main()
  File "restore.py", line 99, in main
    restore_folder(client, root_path, cutoff_datetime, verbose=True)
  File "restore.py", line 87, in restore_folder
    item.get('is_deleted', False), verbose)
  File "restore.py", line 64, in restore_file
    client.restore(path.encode('utf8'), rev)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/client.py", line 1072, in restore
    return self.rest_client.POST(url, params, headers)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 316, in POST
    return cls.IMPL.POST(*n, **kw)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 254, in POST
    post_params=params, headers=headers, raw_response=raw_response)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 227, in request
    raise ErrorResponse(r, r.read())

Only happened once, worked afterwards

**Comment by clark800** [comment]
I don't know, probably a problem with the Dropbox servers.
