### ISSUE TITLE
Internal Server Error (500 & 503)

### ISSUE THREAD

**Issue by kleuter** [clark800/dropbox-restore#38]
Tried to restore one folder, everything worked fine until

```
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Filters/Tiles.8BF 2
015-04-22 12:37:19
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Filters/Twirl.8BF 2
015-04-22 12:37:19
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Filters/VanishingPo
int.8BF 2015-04-22 12:37:19
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Filters/Wave.8BF 20
15-04-22 12:37:19
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Filters/Wind.8BF 20
15-04-22 12:37:19
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Filters/ZigZag.8BF
2015-04-22 12:37:19
Restoring folder: /work/tools/graphic/photoshopportable/app/photoshop/Plug-ins/I
mage Stacks
/work/tools/graphic/photoshopportable/app/photoshop/plug-ins/Image Stacks/statis
tics.8BA 2015-04-22 12:37:27
Traceback (most recent call last):
  File "D:\restore.py", line 113, in <module>
    main()
  File "D:\restore.py", line 109, in main
    restore_folder(client, root_path, cutoff_datetime, verbose=True)
  File "D:\restore.py", line 90, in restore_folder
    restore_folder(client, item['path'], cutoff_datetime, verbose)
  File "D:\restore.py", line 90, in restore_folder
    restore_folder(client, item['path'], cutoff_datetime, verbose)
  File "D:\restore.py", line 90, in restore_folder
    restore_folder(client, item['path'], cutoff_datetime, verbose)
  File "D:\restore.py", line 90, in restore_folder
    restore_folder(client, item['path'], cutoff_datetime, verbose)
  File "D:\restore.py", line 93, in restore_folder
    item.get('is_deleted', False), verbose)
  File "D:\restore.py", line 70, in restore_file
    client.restore(path.encode('utf8'), rev)
  File "C:\Python27\lib\site-packages\dropbox\client.py", line 1078, in restore
    return self.rest_client.POST(url, params, headers)
  File "C:\Python27\lib\site-packages\dropbox\rest.py", line 322, in POST
    return cls.IMPL.POST(*n, **kw)
  File "C:\Python27\lib\site-packages\dropbox\rest.py", line 260, in POST
    is_json_request=is_json_request)
  File "C:\Python27\lib\site-packages\dropbox\rest.py", line 235, in request
    raise ErrorResponse(r, r.read())
dropbox.rest.ErrorResponse: [500] u'Internal Server Error'

D:\>
```

**Comment by kleuter** [comment]
The second error when trying to restore another folder;

```
D:\>restore.py "/Work/Tools/Development/Sublime Text" 2016-03-10
Restoring folder: /Work/Tools/Development/Sublime Text
/work/tools/development/Sublime Text/_ctypes.pyd 2015-04-22 12:31:58
/work/tools/development/Sublime Text/_decimal.pyd 2015-04-22 12:31:58
/work/tools/development/Sublime Text/_elementtree.pyd 2015-04-22 12:31:58
/work/tools/development/Sublime Text/_hashlib.pyd 2015-04-22 12:31:58
Traceback (most recent call last):
  File "D:\restore.py", line 113, in <module>
    main()
  File "D:\restore.py", line 109, in main
    restore_folder(client, root_path, cutoff_datetime, verbose=True)
  File "D:\restore.py", line 93, in restore_folder
    item.get('is_deleted', False), verbose)
  File "D:\restore.py", line 70, in restore_file
    client.restore(path.encode('utf8'), rev)
  File "C:\Python27\lib\site-packages\dropbox\client.py", line 1078, in restore
    return self.rest_client.POST(url, params, headers)
  File "C:\Python27\lib\site-packages\dropbox\rest.py", line 322, in POST
    return cls.IMPL.POST(*n, **kw)
  File "C:\Python27\lib\site-packages\dropbox\rest.py", line 260, in POST
    is_json_request=is_json_request)
  File "C:\Python27\lib\site-packages\dropbox\rest.py", line 235, in request
    raise ErrorResponse(r, r.read())
dropbox.rest.ErrorResponse: [503] Error parsing response body or headers: Body -
 '<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle
 this request.\n</bod Headers - HTTPHeaderDict({'Transfer-Encoding': 'chunked',
'Server': 'nginx', 'Connection': 'keep-alive', 'X-Dropbox-Request-Id': '4191dc6c
a683d6f6550c3ea9654613c6', 'Cache-Control': 'no-cache', 'Date': 'Thu, 17 Mar 201
6 16:52:11 GMT', 'Content-Type': 'text/html'})

D:\>
```

**Comment by clark800** [comment]
This looks like a problem with Dropbox's servers. You can try again and if it still doesn't work you can ask Dropbox about it.

**Comment by kleuter** [comment]
**clark800**
Thank you very much for the script and feedback. Your work saved my day
