### ISSUE TITLE
'module' object has no attribute 'client'

### ISSUE THREAD

**Issue by millschristopherjohn** [clark800/dropbox-restore#49]
Sorry for what is probably a silly mistake. Getting an attribute error (AttributeError: 'module' object has no attribute 'client') at the line: flow = dropbox.client.DropboxOAuth2FlowNoRedirect(APP_KEY, APP_SECRET)

First time doing this, so I used the APP_KEY and APP_SECRET from a randomly-named app I created ("in development" status). I already installed dropbox via pip. No other dropbox.py or anything like that sitting around. What's going on?

**Comment by millschristopherjohn** [comment]
After browsing more, I'm guessing this is related to the API change?

**Comment by TombyT** [comment]
I have the same issue as well.

```
Traceback (most recent call last):
  File "restore.py", line 114, in <module>
    main()
  File "restore.py", line 109, in main
    client = login('token.dat')
  File "restore.py", line 42, in login
    access_token = authorize()
  File "restore.py", line 23, in authorize
    flow = dropbox.client.DropboxOAuth2FlowNoRedirect(APP_KEY, APP_SECRET)
AttributeError: 'module' object has no attribute 'client'
```

**Comment by millschristopherjohn** [comment]
Discovered the problem was related to the API change. There's a partial fix from here: https://github.com/clark800/dropbox-restore/issues/40
